name: pre-commit

on:
  pull_request:
  push:
    branches: [ main ]

jobs:
  run-pre-commit:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        id: setup-python
        uses: actions/setup-python@v5
        with:
          python-version: '3.9'

      # Cache pre-commit's hook environments so repeated runs are fast
      - name: Cache pre-commit env
        uses: actions/cache@v4
        with:
          path: ~/.cache/pre-commit
          key: pre-commit-${{ runner.os }}-${{ steps.setup-python.outputs.python-version }}-${{ hashFiles('.pre-commit-config.yaml') }}
          restore-keys: |
            pre-commit-${{ runner.os }}-${{ steps.setup-python.outputs.python-version }}-

      - name: Install pre-commit
        run: pipx install pre-commit

      - name: Run pre-commit (all files)
        run: pre-commit run --all-files

